name: CI/CD Workflow

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  git-pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: git pull on tiers server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MS_HOSTNAME }}
          username: ${{ secrets.TS_USERNAME }}
          password: ${{ secrets.TS_PASSWORD }}
          script: |
            cd admin-savci
            git switch devopschrist
            git pull origin devopschrist

  pm2-restart:
    runs-on: ubuntu-latest
    needs: git-pull

    steps:
      - name: pm2 restart on main server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MS_HOSTNAME }}
          username: ${{ secrets.MS_USERNAME }}
          password: ${{ secrets.MS_PASSWORD }}
          script: ./deploy-savci.sh
