# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH Connection tiers server for git pulling
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MS_HOSTNAME }}
          username: ${{ secrets.TS_USERNAME }}
          password: ${{ secrets.TS_PASSWORD }}
          script: |
            cd admin-savci
            git switch devopschrist
            git pull origin devopschrist

      - name: SSH Connection main server for running build
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MS_HOSTNAME }}
          username: ${{ secrets.MS_USERNAME }}
          password: ${{ secrets.MS_PASSWORD }}
          script: ./deploy-savci.sh
